canton {
  sequencers {
    sequencer1 {
      storage.type = memory
      public-api.port = 16101
      admin-api.port = 16102
      sequencer.type = BFT
    }
  }

  mediators {
    mediator1 {
      storage.type = memory
      admin-api.port = 16103
    }
  }

  participants {
    participant1 {
      storage.type = memory
      admin-api.port = 6112
      ledger-api.port = 6111
      http-ledger-api.port = 6113
    }

    participant2 {
      storage.type = memory
      admin-api.port = 6122
      ledger-api.port = 6121
      http-ledger-api.port = 6123
    }
  }
}
